tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      set -e
      cd "${GITPOD_REPO_ROOT:-$PWD}"

      sudo apt-get update
      sudo apt-get install -y unzip curl

      curl -sS "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -q awscliv2.zip
      sudo ./aws/install --update

      aws --version
vscode:
  extensions:
    - 42Crunch.vscode-openapi